In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("WheatData.csv")

In [3]:
df

Area  Perimeter  Compactness  Length of kernel  Width of kernel  \
0    15.26      14.84       0.8710             5.763            3.312   
1    14.88      14.57       0.8811             5.554            3.333   
2    14.29      14.09       0.9050             5.291            3.337   
3    13.84      13.94       0.8955             5.324            3.379   
4    16.14      14.99       0.9034             5.658            3.562   
..     ...        ...          ...               ...              ...   
205  12.19      13.20       0.8783             5.137            2.981   
206  11.23      12.88       0.8511             5.140            2.795   
207  13.20      13.66       0.8883             5.236            3.232   
208  11.84      13.21       0.8521             5.175            2.836   
209  12.30      13.34       0.8684             5.243            2.974   

     Asymmetry coeff.  Length of kernel groove  Class  
0               2.221                    5.220      1  
1               1.018                    4.956      1  
2               2.699                    4.825      1  
3               2.259                    4.805      1  
4               1.355                    5.175      1  
..                ...                      ...    ...  
205             3.631                    4.870      3  
206             4.325                    5.003      3  
207             8.315                    5.056      3  
208             3.598                    5.044      3  
209             5.637                    5.063      3  

[210 rows x 8 columns]

In [4]:
df.Class.value_counts()

3    70
2    70
1    70
Name: Class, dtype: int64

In [5]:
X=df.iloc[:,[0,1,2,3,4,5,6]].values
y=df.iloc[:,7].values

In [6]:
X

array([[15.26  , 14.84  ,  0.871 , ...,  3.312 ,  2.221 ,  5.22  ],
       [14.88  , 14.57  ,  0.8811, ...,  3.333 ,  1.018 ,  4.956 ],
       [14.29  , 14.09  ,  0.905 , ...,  3.337 ,  2.699 ,  4.825 ],
       ...,
       [13.2   , 13.66  ,  0.8883, ...,  3.232 ,  8.315 ,  5.056 ],
       [11.84  , 13.21  ,  0.8521, ...,  2.836 ,  3.598 ,  5.044 ],
       [12.3   , 13.34  ,  0.8684, ...,  2.974 ,  5.637 ,  5.063 ]])

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=0)

In [8]:
X_train

array([[18.95  , 16.42  ,  0.8829, ...,  3.755 ,  3.368 ,  6.148 ],
       [13.32  , 13.94  ,  0.8613, ...,  3.073 ,  7.035 ,  5.44  ],
       [16.14  , 14.99  ,  0.9034, ...,  3.562 ,  1.355 ,  5.175 ],
       ...,
       [19.15  , 16.45  ,  0.889 , ...,  3.815 ,  3.084 ,  6.185 ],
       [14.99  , 14.56  ,  0.8883, ...,  3.377 ,  2.958 ,  5.175 ],
       [11.27  , 12.97  ,  0.8419, ...,  2.763 ,  4.309 ,  5.    ]])

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
sc= StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [11]:
X_train

array([[ 1.39839588,  1.40691641,  0.54076511, ...,  1.32859941,
        -0.21222347,  1.48279154],
       [-0.53336705, -0.48148169, -0.44935973, ..., -0.50286234,
         2.23767528,  0.05269791],
       [ 0.43423001,  0.3180417 ,  1.48046692, ...,  0.81031185,
        -1.55709562, -0.48257725],
       ...,
       [ 1.46701978,  1.42975994,  0.82038369, ...,  1.48972508,
        -0.40196201,  1.55752807],
       [ 0.03964256, -0.00938216,  0.78829631, ...,  0.31350771,
        -0.48614179, -0.48257725],
       [-1.23676207, -1.22008901, -1.33863852, ..., -1.33534495,
         0.41645248, -0.83606084]])

In [13]:
from sklearn.svm import SVC

In [22]:
classifier= SVC(kernel='poly',random_state=0,degree=3)
classifier.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [23]:
y_pred= classifier.predict(X_test)

In [24]:
y_pred

array([1, 1, 1, 1, 3, 2, 2, 1, 2, 3, 1, 3, 1, 3, 2, 2, 3, 1, 1, 1, 3, 1,
       1, 1, 2, 1, 2, 1, 3, 3, 1, 3, 1, 1, 3, 3, 3, 2, 1, 1, 3, 1],
      dtype=int64)

In [25]:
from sklearn.metrics import confusion_matrix

In [26]:
cm= confusion_matrix(y_test,y_pred)

In [27]:
cm

array([[13,  0,  0],
       [ 8,  8,  0],
       [ 0,  0, 13]], dtype=int64)

In [20]:
12+14+13

39

In [21]:
39/42

0.9285714285714286

In [28]:
13+8+13

34

In [29]:
34/42

0.8095238095238095